name: CMake on multiple platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
    
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            cpack_flag: DEB
            extension: deb
          - os: ubuntu-latest
            cpack_flag: RPM
            extension: rpm
          - os: ubuntu-latest
            cpack_flag: ZIP
            extension: zip
          - os: ubuntu-latest
            cpack_flag: TGZ
            extension: tar.gz
          - os: windows-latest
            cpack_flag: WIX
            extension: msi
          - os: macos-latest
            cpack_flag: DragNDrop
            extension: dmg
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install rpm

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Create packages
        run: cd build && cpack -G ${{ matrix.cpack_flag }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pack-${{ matrix.extension }}
          path: build/*.${{ matrix.extension }}

  create_release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
       contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - run: mkdir -p artifacts
    - name: download_artefacts
      uses: actions/download-artifact@v4

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.${{ github.run_number }}
        name: Release v1.${{ github.run_number }}
        files: pack-*/*
