name: CMake on multiple platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  create_release:
    runs-on: ubuntu-latest
    permissions:
       contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Docker compose
      run: docker-compose --context remote -f docker-compose.yml up -d
    
    - run: mkdir -p artifacts
    - name: download_artefacts
      uses: actions/download-artifact@v4

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.${{ github.run_number }}
        name: Release v1.${{ github.run_number }}
        files: pack-*/*
