name: CMake on multiple platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
       contents: write
       
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: sudo docker build -t hello_world . 

    - name: Run
      run: docker run --name hw_app hello_world

    - name: Copy
      run: sudo docker cp hw_app:building/hello_world_application/hw_app .
      
    - run: mkdir -p artifacts
    - name: download_artefacts
      uses: actions/download-artifact@v4
      
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.${{ github.run_number }}
        name: Release v1.${{ github.run_number }}
        files: hello_world
